name: Snyk Infrastructure as Code
on: 
  workflow_dispatch
jobs:
  snyk:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check configuration files for security issues
        run: snyk iac test
